version: "3.7"

services:
  # api-gateway:
  #   build: ../../Epilepsy_Health_App.APIGateway
  #   container_name: api-gateway
  #   restart: unless-stopped
  #   ports:
  #     - 5000:80
  #   networks:
  #     - epilepsy_health_app

  identity-service:
    build: ../../Epilepsy_Health_App.Services.Identity
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5001:5001
    networks:
      - epilepsy_health_app
    
  # healthdata-service:
  #   build: ../../Epilepsy_Health_App.Services.HealthData
  #   container_name: healthdata-service
  #   restart: unless-stopped
  #   ports:
  #     - 5002:80
  #   networks:
  #     - epilepsy_health_app

networks:
  epilepsy_health_app:
    name: epilepsy_health_app-network
    external: true